=== winnerdev2012/firefly/core/src/schemas/config.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "port",
    "assetTrailInstanceID",
    "protocol",
    "apiGateway",
    "eventStreams",
    "ipfs",
    "app2app",
    "docExchange",
    "appCredentials"
  ],
  "properties": {
    "port": {
      "type": "integer"
    },
    "assetTrailInstanceID": {
      "type": "string"
    },
    "protocol": {
      "type": "string",
      "enum": ["ethereum", "corda"]
    },
    "apiGateway": {
      "type": "object",
      "required": [
        "apiEndpoint"
      ],
      "properties": {
        "apiEndpoint": {
          "type": "string"
        }, 
        "auth": {
          "type": "object",
          "required": [
            "user",
            "password"
          ],
          "properties": {
            "user": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          }
        }
      }
    },
    "eventStreams": {
      "type": "object",
      "required": [
        "wsEndpoint",
        "topic"
      ],
      "properties": {
        "wsEndpoint": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "skipSetup": {
          "type": "boolean"
        },
        "auth": {
          "type": "object",
          "required": [
            "user",
            "password"
          ],
          "properties": {
            "user": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          }
        }
      }
    },
    "ipfs": {
      "type": "object",
      "required": [
        "apiEndpoint"
      ],
      "properties": {
        "apiEndpoint": {
          "type": "string"
        },
        "gatewayEndpoint": {
          "type": "string"
        }
      }
    },
    "app2app": {
      "type": "object",
      "required": [
        "socketIOEndpoint",
        "destinations"
      ],
      "properties": {
        "socketIOEndpoint": {
          "type": "string"
        },
        "destinations": {
          "type": "object",
          "required": [
            "kat",
            "client"
          ],
          "properties": {
            "kat": {
              "type": "string"
            },
            "client": {
              "type": "string"
            }
          }
        }
      }
    },
    "docExchange": {
      "type": "object",
      "required": [
        "apiEndpoint",
        "socketIOEndpoint",
        "destination"
      ],
      "properties": {
        "apiEndpoint": {
          "type": "string"
        },
        "socketIOEndpoint": {
          "type": "string"
        },
        "destination": {
          "type": "string"
        }
      }
    },
    "appCredentials": {
      "type": "object",
      "required": [
        "user",
        "password"
      ],
      "properties": {
        "user": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "mongodb": {
      "type": "object",
      "required": [
        "connectionUrl",
        "databaseName"
      ],
      "connectionUrl": {
        "type": "string"
      },
      "databaseName": {
        "type": "string"
      }
    }
  }
}

=== winnerdev2012/firefly/kat/data/single-region/OrgA/config.json
{
  "$schema": "../../../src/schemas/config.json",
  "port": 4001,
  "assetTrailInstanceID": "asset-trail-org-a",
  "protocol": "ethereum",
  "apiGateway": {
    "apiEndpoint": "https://zzkuwhhizm-zzhh7vdg4w-connect.dev2.photic.io/instances/0x2af2b71292fcb2af2423b1820cfb0d6e2be2c4a4"
  },
  "eventStreams": {
    "wsEndpoint": "wss://zzkuwhhizm-zzhh7vdg4w-connect.dev2-ws.photic.io/ws",
    "topic": "synaptic"
  },
  "ipfs": {
    "apiEndpoint": "https://zzkuwhhizm-zzh1ibg3o0-ipfs.dev2.photic.io"
  },
  "app2app": {
    "socketIOEndpoint": "wss://zzkuwhhizm-zzigaja3ua.dev2-ws.photic.io/api/v1",
    "destinations": {
      "kat": "kld://app2app/z/dev2/m/zzxknul1nt/e/zzkuwhhizm/s/zzigaja3ua/d/a",
      "client": "kld://app2app/z/dev2/m/zzxknul1nt/e/zzkuwhhizm/s/zzigaja3ua/d/external"
    }
  },
  "docExchange": {
    "apiEndpoint": "https://zzkuwhhizm-zzpp1ys1l8-documentstore.dev2.photic.io/api/v1",
    "socketIOEndpoint": "wss://zzkuwhhizm-zzpp1ys1l8.dev2-ws.photic.io/api/v1",
    "destination": "kld://documentstore/z/dev2/m/zzxknul1nt/e/zzkuwhhizm/s/zzpp1ys1l8/d/a"
  },
  "appCredentials": {
    "user": "zzbvccppd3",
    "password": "_WOhsqQ6ee8pW39Surq9XkZvP4Al-hjDNoFaKUQQF20"
  },
  "mongodb": {
    "connectionUrl": "mongodb://localhost:27017",
    "databaseName": "synaptic-sr-org-a"
  }
}

=== winnerdev2012/firefly/kat/data/multi-region/OrgB/config.json
{
  "$schema": "../../../src/schemas/config.json",
  "port": 4002,
  "assetTrailInstanceID": "asset-trail-org-b",
  "protocol": "ethereum",
  "apiGateway": {
    "apiEndpoint": "https://zzdk0au9rl-zzxtrleuk4-connect.azdev.photic.io/instances/0xc4ed58b23059e5b2f867b6040b46dcea04396c8b"
  },
  "eventStreams": {
    "wsEndpoint": "wss://zzdk0au9rl-zzxtrleuk4-connect.azdev-ws.photic.io/ws",
    "topic": "B"
  },
  "ipfs": {
    "apiEndpoint": "https://zzdk0au9rl-zzd1ddssj0-ipfs.azdev.photic.io"
  },
  "app2app": {
    "socketIOEndpoint": "wss://zzdk0au9rl-zzyy8m38ff.azdev-ws.photic.io/api/v1",
    "destinations": {
      "kat": "kld://app2app/z/azdev/m/zzzohltm98/e/zzdk0au9rl/s/zzyy8m38ff/d/kat",
      "client": "kld://app2app/z/azdev/m/zzzohltm98/e/zzdk0au9rl/s/zzyy8m38ff/d/client"
    }
  },
  "docExchange": {
    "apiEndpoint": "https://zzdk0au9rl-zzleq01yh6-documentstore.azdev.photic.io/api/v1",
    "socketIOEndpoint": "wss://zzdk0au9rl-zzleq01yh6.azdev-ws.photic.io/api/v1",
    "destination": "kld://documentstore/z/azdev/m/zzzohltm98/e/zzdk0au9rl/s/zzleq01yh6/d/b"
  },
  "appCredentials": {
    "user": "zzv7dyg5d0",
    "password": "2tyAt2ZaavAd76jmzP01X6fhAvp8pmh2qoLXkgBm2ps"
  },
  "mongodb": {
    "connectionUrl": "mongodb://localhost:27017",
    "databaseName": "synaptic-mr-org-b"
  }
}

=== winnerdev2012/firefly/kat/test-resources/config-ethereum.json
{
  "$schema": "../src/schemas/config.json",
  "port": 3000,
  "protocol": "ethereum",
  "assetTrailInstanceID": "service-id",
  "apiGateway": {
    "apiEndpoint": "https://apigateway.kaleido.io"
  },
  "eventStreams": {
    "wsEndpoint": "ws://eventstreams.kaleido.io",
    "topic": "dev",
    "skipSetup": true
  },
  "ipfs": {
    "apiEndpoint": "https://ipfs.kaleido.io"
  },
  "app2app": {
    "socketIOEndpoint": "wss://app2app.ws.kaleido.io",
    "destinations": {
      "kat": "kld://app2app/internal",
      "client": "kld://app2app/external"
    }
  },
  "docExchange": {
    "apiEndpoint": "https://docexchange.kaleido.io",
    "socketIOEndpoint": "http://docexchange.ws.kaleido.io",
    "destination": "kld://docstore/dest"
  },
  "appCredentials": {
    "user": "testuser",
    "password": "testpassword"
  }
}

=== winnerdev2012/firefly/core/data/multi-region/OrgA/config.json
{
  "$schema": "../../../src/schemas/config.json",
  "port": 4001,
  "assetTrailInstanceID": "asset-trail-org-a",
  "protocol": "ethereum",
  "apiGateway": {
    "apiEndpoint": "https://zzdk0au9rl-zznm62sm1o-connect.dev2.photic.io/instances/0xc4ed58b23059e5b2f867b6040b46dcea04396c8b"
  },
  "eventStreams": {
    "wsEndpoint": "wss://zzdk0au9rl-zznm62sm1o-connect.dev2-ws.photic.io/ws",
    "topic": "A"
  },
  "ipfs": {
    "apiEndpoint": "https://zzdk0au9rl-zzrgeqp403-ipfs.dev2.photic.io"
  },
  "app2app": {
    "socketIOEndpoint": "wss://zzdk0au9rl-zzspcgumw6.dev2-ws.photic.io/api/v1",
    "destinations": {
      "kat": "kld://app2app/z/dev2/m/zzdza6cuf9/e/zzdk0au9rl/s/zzspcgumw6/d/kat",
      "client": "kld://app2app/z/dev2/m/zzdza6cuf9/e/zzdk0au9rl/s/zzspcgumw6/d/client"
    }
  },
  "docExchange": {
    "apiEndpoint": "https://zzdk0au9rl-zzu2yrgdqw-documentstore.dev2.photic.io/api/v1",
    "socketIOEndpoint": "wss://zzdk0au9rl-zzu2yrgdqw.dev2-ws.photic.io/api/v1",
    "destination": "kld://documentstore/z/dev2/m/zzdza6cuf9/e/zzdk0au9rl/s/zzu2yrgdqw/d/a"
  },
  "appCredentials": {
    "user": "zzzpyzyey1",
    "password": "RVSTBdP1N9_XVPWzNbKJmTpgfM6dtKECwEdcfk3Kctw"
  },
  "mongodb": {
    "connectionUrl": "mongodb://localhost:27017",
    "databaseName": "synaptic-mr-org-a"
 }
}

=== winnerdev2012/firefly/core/test-resources/config-corda.json
{
    "$schema": "../src/schemas/config.json",
    "port": 3001,
    "protocol": "corda",
    "assetTrailInstanceID": "service-id",
    "apiGateway": {
      "apiEndpoint": "https://apigateway.kaleido.io",
      "auth": {
        "user": "testuser",
        "password": "testpassword"
      }
    },
    "eventStreams": {
      "wsEndpoint": "ws://eventstreams.kaleido.io",
      "topic": "dev",
      "auth": {
        "user": "testuser",
        "password": "testpassword"
      }
    },
    "ipfs": {
      "apiEndpoint": "https://ipfs.kaleido.io"
    },
    "app2app": {
      "socketIOEndpoint": "wss://app2app.ws.kaleido.io",
      "destinations": {
        "kat": "kld://app2app/internal",
        "client": "kld://app2app/external"
      }
    },
    "docExchange": {
      "apiEndpoint": "https://docexchange.kaleido.io",
      "socketIOEndpoint": "http://docexchange.ws.kaleido.io",
      "destination": "kld://docstore/dest"
    },
    "appCredentials": {
      "user": "testuser",
      "password": "testpassword"
    }
  }

=== winnerdev2012/firefly/kat/data/single-region/OrgB/config.json
{
  "$schema": "../../../src/schemas/config.json",
  "port": 4002,
  "assetTrailInstanceID": "asset-trail-org-b",
  "protocol": "ethereum",
  "apiGateway": {
    "apiEndpoint": "https://zzkuwhhizm-zzyi4f2hqt-connect.dev2.photic.io/instances/0x2af2b71292fcb2af2423b1820cfb0d6e2be2c4a4"
  },
  "eventStreams": {
    "wsEndpoint": "wss://zzkuwhhizm-zzyi4f2hqt-connect.dev2-ws.photic.io/ws",
    "topic": "synaptic"
  },
  "ipfs": {
    "apiEndpoint": "https://zzkuwhhizm-zzvosyrz5t-ipfs.dev2.photic.io"
  },
  "app2app": {
    "socketIOEndpoint": "wss://zzkuwhhizm-zzcpoj78bh.dev2-ws.photic.io/api/v1",
    "destinations": {
      "kat": "kld://app2app/z/dev2/m/zzt1fril6n/e/zzkuwhhizm/s/zzcpoj78bh/d/b",
      "client": "kld://app2app/z/dev2/m/zzt1fril6n/e/zzkuwhhizm/s/zzcpoj78bh/d/external"
    }
  },
  "docExchange": {
    "apiEndpoint": "https://zzkuwhhizm-zzwt65yyp0-documentstore.dev2.photic.io/api/v1",
    "socketIOEndpoint": "wss://zzkuwhhizm-zzwt65yyp0.dev2-ws.photic.io/api/v1",
    "destination": "kld://documentstore/z/dev2/m/zzt1fril6n/e/zzkuwhhizm/s/zzwt65yyp0/d/b"
  },
  "appCredentials": {
    "user": "zzwfeybeli",
    "password": "PiinAvy8PkwP3bBbXw0TrX_fzvBw4KTYtTQzS1QE4zs"
  },
  "mongodb": {
    "connectionUrl": "mongodb://localhost:27017",
    "databaseName": "synaptic-sr-org-b"
  }
}
